---
  name: Cache Maker

  on:
    workflow_dispatch:

  jobs:
    compile_sketch:
      name: Cache maker
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v5
            with:
              submodules: true

          - id: build
            name: setup Python
            uses: actions/setup-python@v6
            with:
              python-version: "3.13"

          - name: Cache pip
            uses: actions/cache@v5
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
                ${{ runner.os }}-pip-

          - name: Cache PlatformIO Framework
            uses: actions/cache@v5
            with:
              path: |
                .pio/core
              key: ${{ runner.os }}-platformio-${{ hashFiles('platformio.ini') }}
              restore-keys: |
                ${{ runner.os }}-platformio-${{ hashFiles('platformio.ini') }}
                ${{ runner.os }}-platformio-

          - name: Install dependencies
            run: |
              pip install requests esptool platformio

          - name: Fetch tools for Xtensa
            run: |
              platformio run -e headless-esp32-4mb

          - name: Fetch tools for RISCV
            run: |
              platformio run -e NM-CYD-C5
